# Site settings
title: "Wonjun Ko Resume"
description: "A resume for Wonjun Ko, Ph.D."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Wonjun Ko, Ph.D."
resume_title:                   "Data Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "dwight1014@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+82 2-3290-3738"
resume_contact_address:         "Science Library 510, Korea University, Anam-ro 145, Seongbuk-gu, Seoul, Republic of Korea"

# resume_header_contact_info:     "Science Library 510, Korea University, Anam-ro 145, Seongbuk-gu, Seoul, Republic of Korea • +82 2-3290-3738 • dwight1014@gmail.com"
resume_header_contact_info:     "Ph.D. degree will be conferred in August 2022 • +82 2-3290-3738 • dwight1014@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I received the B.S. degree in physics from Sogang University, Seoul, Republic of Korea, in 2017. I also received the Ph.D. degree in brain and cognitive engineering from Korea University, Seoul, Republic of Korea, in 2022. My current research interests include machine learning, deep learning, representation learning, and Bayesian learning.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/wko1014"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/wonjun-ko-30475a19a/"
  resume_instagram_url:         "https://www.instagram.com/wko1014/"
  resume_website_url:           "https://sites.google.com/korea.ac.kr/wonjun-ko/home"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
